# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = 'HRAG'
copyright = '2025, Guohang Yan, Pinlong Cai, Ding Wang, Song Mao'
author = 'Guohang Yan, Pinlong Cai, Ding Wang, Song Mao'
release = 'v1.0.0'
version = '1.0.0'

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

# Add any Sphinx extension module names here, as strings
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'sphinx.ext.viewcode',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.githubpages',
    'sphinx.ext.autosummary',
    'sphinx.ext.doctest',
    'sphinx.ext.ifconfig',
    'sphinx.ext.extlinks',
    'sphinx_copybutton',
    'sphinx_rtd_theme',
    'myst_parser',
]

# Add any paths that contain templates here, relative to this directory
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files
exclude_patterns = [
    '_build',
    'Thumbs.db',
    '.DS_Store',
    '*.pyc',
    '__pycache__',
    'venv',
    '.venv',
    'env',
    '.env',
    'node_modules',
    '*.egg-info',
    'dist',
    'build',
]

# The suffix of source filenames
source_suffix = {
    '.rst': 'restructuredtext',
    '.md': 'markdown',
}

# The encoding of source files
source_encoding = 'utf-8'

# The master toctree document
master_doc = 'index'

# The language for content autogenerated by Sphinx
language = 'zh_CN'

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
# today = ''
# Else, today_fmt is used as the format for a strftime call
today_fmt = '%Y年%m月%d日'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files
# This pattern also affects html_static_path and html_extra_path
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing
todo_include_todos = True

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

# The theme to use for HTML and HTML Help pages
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation
html_theme_options = {
    'navigation_depth': 4,
    'collapse_navigation': False,
    'sticky_navigation': True,
    'includehidden': True,
    'titles_only': False,
    'display_version': True,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': True,
    'style_nav_header_background': '#2980B9',
    'logo_only': False,
    'canonical_url': '',
    'analytics_id': '',
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css"
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names
html_sidebars = {
    '**': [
        'about.html',
        'navigation.html',
        'relations.html',
        'searchbox.html',
        'donate.html',
    ]
}

# The name of an image file (relative to this directory) to place at the top
# of the sidebar
html_logo = '_static/logo.png'

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large
html_favicon = '_static/favicon.ico'

# Output file base name for HTML help builder
htmlhelp_basename = 'HRAGdoc'

# -- Options for LaTeX output ------------------------------------------------
latex_elements = {
    # The paper size ('letterpaper' or 'a4paper')
    'papersize': 'a4paper',
    # The font size ('10pt', '11pt' or '12pt')
    'pointsize': '12pt',
    # Additional stuff for the LaTeX preamble
    'preamble': '',
    # Latex figure (float) alignment
    'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class])
latex_documents = [
    (master_doc, 'HRAG.tex', 'HRAG Documentation',
     'Guohang Yan, Pinlong Cai, Ding Wang, Song Mao', 'manual'),
]

# -- Options for manual page output ------------------------------------------
# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section)
man_pages = [
    (master_doc, 'hrag', 'HRAG Documentation',
     [author], 1)
]

# -- Options for Texinfo output ----------------------------------------------
# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'HRAG', 'HRAG Documentation',
     author, 'HRAG', 'Hybrid Retrieval-Augmented Generation System',
     'Miscellaneous'),
]

# -- Options for Epub output -------------------------------------------------
# Bibliographic Dublin Core info
epub_title = project
epub_author = author
epub_publisher = author
epub_copyright = copyright

# The unique identifier of the text. This can be a ISBN number
# or the project homepage
epub_identifier = 'https://github.com/your-github-username/hrag'

# A unique identification for the text
epub_uid = 'HRAG'

# A list of files that should not be packed into the epub file
epub_exclude_files = ['search.html']

# -- Extension configuration -------------------------------------------------

# Intersphinx mapping
intersphinx_mapping = {
    'python': ('https://docs.python.org/3/', None),
    'numpy': ('https://numpy.org/doc/stable/', None),
    'pandas': ('https://pandas.pydata.org/docs/', None),
    'torch': ('https://pytorch.org/docs/stable/', None),
    'transformers': ('https://huggingface.co/docs/transformers/', None),
    'fastapi': ('https://fastapi.tiangolo.com/', None),
    'pydantic': ('https://docs.pydantic.dev/', None),
}

# Napoleon settings
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_preprocess_types = False
napoleon_type_aliases = None
napoleon_attr_annotations = True

# Autodoc settings
autodoc_default_options = {
    'members': True,
    'member-order': 'bysource',
    'special-members': '__init__',
    'undoc-members': True,
    'exclude-members': '__weakref__',
    'show-inheritance': True,
    'inherited-members': True,
}

autodoc_mock_imports = [
    'torch',
    'transformers',
    'numpy',
    'pandas',
    'fastapi',
    'pydantic',
    'uvicorn',
    'gunicorn',
    'pymilvus',
    'elasticsearch',
    'neo4j',
    'mysql.connector',
    'pymongo',
    'redis',
    'faiss',
    'chromadb',
    'langchain',
    'langchain_experimental',
    'gradio',
    'streamlit',
    'mlflow',
    'tensorboard',
    'optuna',
    'hyperopt',
    'dask',
    'pyspark',
    'psutil',
    'hydra',
    'dvc',
    'git',
    'supervisor',
    'systemd',
]

# Autosummary settings
autosummary_generate = True

# Copy button settings
copybutton_prompt_text = r">>> |\.\.\. |\$ |In \[\d*\]: | {2,5}\.\.\.: | {5,8}: "
copybutton_prompt_is_regexp = True
copybutton_line_continuation_character = "\\"

# External links
extlinks = {
    'issue': ('https://github.com/your-github-username/hrag/issues/%s', 'Issue #%s'),
    'pr': ('https://github.com/your-github-username/hrag/pull/%s', 'PR #%s'),
    'commit': ('https://github.com/your-github-username/hrag/commit/%s', 'Commit %s'),
}

# MathJax configuration
mathjax_config = {
    'TeX': {
        'equationNumbers': {'autoNumber': 'AMS'},
        'extensions': ['AMSmath.js', 'AMSsymbols.js'],
    },
}

# MyST Parser settings
myst_enable_extensions = [
    "amsmath",
    "colon_fence",
    "deflist",
    "dollarmath",
    "html_image",
    "html_admonition",
    "replacements",
    "smartquotes",
    "substitution",
    "tasklist",
]

# -- Options for internationalization ----------------------------------------
# The language for content autogenerated by Sphinx
language = 'zh_CN'

# Locale settings
locale_dirs = ['locale/']
gettext_compact = False

# -- Options for linkcheck --------------------------------------------------
# Link check settings
linkcheck_ignore = [
    r'http://localhost:\d+',
    r'http://127.0.0.1:\d+',
    r'https://github.com/.*#.*',
]

# -- Options for coverage ---------------------------------------------------
# Coverage settings
coverage_show_missing_items = True
coverage_html_dir = '_build/coverage'

# -- Options for todo ------------------------------------------------------
# Todo settings
todo_include_todos = True
todo_link_only = True

# -- Options for viewcode --------------------------------------------------
# Viewcode settings
viewcode_follow_imports_missing = True

# -- Options for githubpages -------------------------------------------------
# GitHub Pages settings
html_baseurl = 'https://your-repo-owner.github.io/hrag/'

# -- Project-specific settings ----------------------------------------------
# Add any project-specific settings here

# Suppress warnings
suppress_warnings = [
    'autosectionlabel.*',
    'toc.excluded',
]

# Add custom CSS
def setup(app):
    app.add_css_file('custom.css')
    app.add_js_file('custom.js')
